import os
from dotenv import load_dotenv
from app.services.google_slides_service import GoogleSlidesService

# Load env to get Template ID
load_dotenv()

def test_generation():
    print("🚀 Starting Google Slides Test...")
    
    template_id = os.getenv("GOOGLE_SLIDES_TEMPLATE_ID")
    if not template_id:
        print("❌ Error: GOOGLE_SLIDES_TEMPLATE_ID not found in .env")
        return

    print(f"📋 Using Template ID: {template_id}")
    
    try:
        service = GoogleSlidesService()
        print("✅ Authentication successful")
        
        # 1. Create Presentation
        print("1️⃣  Creating new presentation from template...")
        presentation_id = service.create_presentation_from_template(
            "TEST PRESENTATION - OceanAI", 
            template_id
        )
        print(f"   -> Created ID: {presentation_id}")
        
        # 2. Inspect Slides
        print("2️⃣  Inspecting slides...")
        slides = service.get_presentation_slides(presentation_id)
        print(f"   -> Found {len(slides)} slides")
        
        if len(slides) < 2:
            print("⚠️  Warning: Template has fewer than 2 slides. Content generation might fail if it expects Title + Body slides.")
            
        # 3. Test Replacement
        print("3️⃣  Testing text replacement...")
        
        # Title Slide Replacement
        print("   -> Replacing Title Slide placeholders...")
        service.replace_text(presentation_id, {
            "{{MAIN_TITLE}}": "OceanAI Test Run",
            "{{SUBTITLE}}": "Automated Generation Test"
        }, slide_ids=[slides[0]['objectId']])
        
        # Content Slide Duplication & Replacement
        if len(slides) > 3:
            print("   -> Duplicating Content Slide (Index 3)...")
            content_slide_id = slides[3]['objectId']
            new_slide_id = service.duplicate_slide(presentation_id, content_slide_id)
            print(f"      -> New Slide ID: {new_slide_id}")
            
            print("   -> Replacing Content Slide placeholders...")
            service.replace_text(presentation_id, {
                "{{SLIDE_TITLE}}": "Test Slide 1",
                "{{SLIDE_CONTENT}}": "• Bullet point 1\n• Bullet point 2\n• Generated by API"
            }, slide_ids=[new_slide_id])
            
        print("✅ Test Complete!")
        print(f"🎉 View your presentation here: https://docs.google.com/presentation/d/{presentation_id}/edit")
        
        # Note: We are NOT deleting it so you can view it.
        # In production, we export to bytes and then delete.

    except Exception as e:
        print(f"❌ Error during test: {e}")

if __name__ == "__main__":
    test_generation()
